# Generated by Django 4.0.2 on 2022-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_url_long_url_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
