# Generated by Django 4.0.2 on 2022-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_url_last_visit_alter_url_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='url',
            name='last_visit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
